name: tfew
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch::*=*cuda*
  - pytorch::pytorch-cuda
  - conda-forge::torchvision
  - conda-forge::torchaudio
  - conda-forge::transformers
  - conda-forge::pytorch-lightning
  - conda-forge::datasets
  - conda-forge::torchmetrics
  - conda-forge::psutil
  - conda-forge::sentencepiece
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::tensorboard
  - pip
  - pip:
    - promptsource
    - deepspeed
